# Machine learning
## Chapter 4, Vector and Matrix
## Jun Sup Shin, Digital Imaging, GASIM, CAU

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

## `np.ndarray`
* For vectors, use `np.array` to create `np.ndarray` class
* `np.array` creates `np.ndarray` object using python `list`
* To use linear algebra stuffs, use two bracket of list
   * `[[...]]`
   * `[[], [], []]`

In [2]:
row_x = np.array([[1, 2, 3]])
print("row vector of x", row_x)

col_x = row_x.T # transpose
print("column vector of x")
print(col_x)

row vector of x [[1 2 3]]
column vector of x
[[1]
 [2]
 [3]]


## Arithmetic of vectors
* you can use basic arithmetic of vector by using default python operator
   * or you can use numpy functions 
* basic operation for multiplication is **element-wise multiplication**
   * use `dot` for dot product
* shape needs to be same to get expected behavior or avoid error

In [3]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 2, 2]])

print("a+b  = ", a+b)    # np.add(a, b)
print("a-b  = ", a-b)    # np.subtract(a, b)
print("a*b  = ", a*b)    # np.multiply(a, b)       * element-wise multiplication
print("a*3  = ", a*3)    # np.multiply(a, scalar)
print("a/b  = ", a/b)    # np.divide(a, b)
print("a**b = ", a**b)   # np.power(a, b)
print("a//b = ", a//b)   # np.divmod(a, b)[0]
print("a%b  = ", a%b)    # np.divmod(a, b)[1]

print("\na.dot(b.T) = ", a.dot(b.T))
print("np.cross(a, b) = ", np.cross(a, b))

a+b  =  [[3 4 5]]
a-b  =  [[-1  0  1]]
a*b  =  [[2 4 6]]
a*3  =  [[3 6 9]]
a/b  =  [[0.5 1.  1.5]]
a**b =  [[1 4 9]]
a//b =  [[0 1 1]]
a%b  =  [[1 0 1]]

a.dot(b.T) =  [[12]]
np.cross(a, b) =  [[-2  4 -2]]


## Matrix by `np.ndarray`
* can also use `np.array` to create matrix as 2D array
* arithmetic can be used exactly same as vector
   * notice that basic operations of `np.ndarray` is **element-wise** operations
* for matrix multiplication you can use one of bellow two
   * `A.dot(B)`
   * `np.matmul(A, B)`

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [2, 1]])

print("Element-wise multiplication\n", A*B)
print("Matrix multiplication via dot\n", A.dot(B))
print("Matrix multiplication via matmul\n", np.matmul(A, B))

Element-wise multiplication
 [[2 6]
 [6 4]]
Matrix multiplication via dot
 [[ 6  5]
 [14 13]]
Matrix multiplication via matmul
 [[ 6  5]
 [14 13]]


## Matrix by `np.matrix`
* specialized `np.ndarray` for 2 dimension
* multiplication(`*`) is matrix multiplication
* `A ** n` is matrix product $A^{n}$
* supports `.H` for conjugate transpose, `.I` for inverse matrix

In [5]:
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[2, 3], [2, 1]])
print("matrix multiplication \n", A * B)

print("\nmatrix power A^2\n", A**2)
print("matrix power A*A\n", A*A)
print("np.power\n", np.power(A, 2))

matrix multiplication 
 [[ 6  5]
 [14 13]]

matrix power A^2
 [[ 7 10]
 [15 22]]
matrix power A*A
 [[ 7 10]
 [15 22]]
np.power
 [[ 1  4]
 [ 9 16]]


## `np.ndarray` vs `np.matrix`
* it seems like using `np.matrix` is more usefull and intuitive
* From googling, I found out that `np.matrix` is somewhat **deprecated**
* There are limitations for `np.matrix`
   * Cannot handle 3 or more dimensional objects (tensor)
   * mixing `np.ndarray` and `np.matrix` annoies programmer
* converting between two is possible
   * `np.asarray`, `np.asmatrix`

from my experience, I prefer using `np.ndarray` from above limitations but also because
* Since python is dynamic typed language, it is hard for me to identify the type when debugging
* explicitly use `np.*` functions instead python operators
   * for example, I never use element-wise multiplication operator `*` for np.ndarray
   * I always use `np.multiply` or `np.matmul` for multiplication
   * for some special situations, I use `np.matrix` for only temporary  variables

In [6]:
A = np.array([[1, 2], [2, 3]])

# when I want np.matrix operations...
B = np.asarray(np.asmatrix(A)**5)

## `np.linalg`
numpy package for linear algebra

### Some useful functions
#### Matrix operations
* `np.linalg.matrix_power` : matrix power product
#### Decomposition
* `np.linalg.cholesky` : cholesky decomposition
* `np.linalg.qr` : QR decomposition
* `np.linalg.svd` : SVD decomposition
#### Eigen values
* `np.linalg.eig` : compute eigen value
#### Numbers
* `np.linalg.det` : determinant
* `np.linalg.norm` : norm(L2)
* `np.linalg.matrix_rank` : rank
* `np.linalg.trance` : trace
#### Solving equations
* `np.linalg.solve` : solve linear equations
* `np.linalg.lstsq` : least square solution
* `np.linalg.inv` : inverse
* `np.linalg.pinv` : pseudo inverse